name: manifest
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"   # täglich um 00:00 UTC

permissions:
  contents: write

jobs:
  build-manifest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run builder
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FW_REPOS: Samsemillia89/AOT-Controller,Samsemillia89/AOT-Display
          FW_CHANNEL: stable
        run: |
          python3 manifest_builder.py

      - name: Commit to gh-pages
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github"
          git checkout -B gh-pages
          mv firmware.json index.json
          git add index.json
          git commit -m "Update manifest"
          git push -f origin gh-pages
